version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - mysql:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: redhat
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wpadmin
       MYSQL_PASSWORD: wpadmin

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wpadmin
       WORDPRESS_DB_PASSWORD: wpadmin
       WORDPRESS_DB_NAME: wordpress
volumes:
    mysql: {}
